#!/bin/sh
python cmp_range.py knn letter 1 &
python cmp_range.py knn letter 2 &
python cmp_range.py knn letter 3 &
python cmp_range.py knn letter 4 &
python cmp_range.py knn letter 5 &
python cmp_range.py knn sat 1 &
python cmp_range.py knn sat 2 &
python cmp_range.py knn sat 3 &
python cmp_range.py knn sat 4 &
python cmp_range.py knn sat 5 &
python cmp_range.py svm letter 1 &
python cmp_range.py svm letter 2 &
python cmp_range.py svm letter 3 &
python cmp_range.py svm letter 4 &
python cmp_range.py svm letter 5 &
python cmp_range.py svm sat 1 &
python cmp_range.py svm sat 2 &
python cmp_range.py svm sat 3 &
python cmp_range.py svm sat 4 &
python cmp_range.py svm sat 5 &